root: true
extends: ['@typescord', prettier]
plugins: [prettier]
parserOptions:
  sourceType: module
  project: tsconfig.json
rules:
  prettier/prettier: error
  import/no-unresolved: off
  unicorn/prevent-abbreviations: off
env:
  node: true
